# 使用的手机操作系统
platformName: Android
# 手机操作系统的版本
platformVersion: 9.0
# 使用的手机或模拟器类型
deviceName: HUAWEI P20 Pro
# 本地绝对路径_或_远程 http URL 所指向的一个安装包（.ipa,.apk,或 .zip 文件）。Appium 将其安装到合适的设备上
#app: C:\Users\ryan.sun\Downloads\djipilot-Official-release-v1.4.0-19292-20190522-2110.apk
# 连接真机的唯一设备号
udid: AKC0218427000227
# 运行的 Android 应用的包名
appPackage: dji.go.v5
# Activity 的名字是指从你的包中所要启动的 Android acticity。他通常需要再前面添加. （例如 使用 .MainActivity 代替 MainActivity）
appActivity: com.dji.component.application.activity.DJILauncherActivity
# 在当前 session 下不会重置应用的状态。默认值为 false
noReset: true
# 使用 Unicode 输入法。 默认值为 false，输入中文时需要设置
unicodeKeyboard: true
# 在设定了unicodeKeyboard关键字的Unicode测试结束后，重置输入法到原有状态。如果单独使用，将会被忽略。默认值为 false
resetKeyboard: true
# Appium 1.6.3开始支持识别Toast内容，主要是基于UiAutomator2
automationName: uiautomator2
# 手机IP地址
ip: 127.0.0.1
# 连接端口
port: 4723
